apiVersion: v1
kind: Service
metadata:
  name: activemq
  labels:
    app: {{ template "activemq.fullname" . }}
    chart: "{{ template "activemq.chart" . }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
spec:
  ports:
    - port: {{ .Values.service.webPort }}
      name: webport
    - port: {{ .Values.service.jmsPort }}
      name: jmsport
  selector:
    app: {{ template "activemq.fullname" . }}
    tier: activemq